version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      all-minor-and-patch-dependency-updates:
        applies-to: version-updates
        patterns:
          - "*"
        exclude-patterns:
          - "pydantic"  # related to https://github.com/ssec-jhu/evolver-ng/issues/213
        update-types:
          - "minor"
          - "patch"
